server:
  port: 9094
  forward-headers-strategy: framework
  servlet:
    context-path: /test/jsonb
spring:
  application:
    name: validator
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:172.27.16.1}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:pessoa}?ApplicationName=${spring.application.name}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  mvc:
    json:
      schema:
        location: classpath:/schema/

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      hibernate:
        default_schema: PESSOAS
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

environment:
    postgres-host: ${POSTGRES_HOST:172.27.16.1}
    postgres-port: ${POSTGRES_PORT:5432}
    postgres-database: ${POSTGRES_DATABASE:pessoa}
    postgres-username: ${POSTGRES_USERNAME:postgres}
    postgres-password: ${POSTGRES_PASSWORD:root}