server:
  port: 9094
  forward-headers-strategy: framework
  servlet:
    context-path: /test/jsonb
spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:nsweb}?ApplicationName=${spring.application.name}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      org:
        hibernate:
          envers:
            audit_table_prefix: AUDITORIA_
            audit_table_suffix:
            revision_field_name: AUDI_SQ_AUDITORIA
            revision_type_field_name: AUDI_NR_AUDITORIA
            default_schema: AUDITORIA
      hibernate:
        default_schema: ARQUIVO
        dialect: org.hibernate.dialect.PostgreSQLDialect
