server:
  port: 9094
  forward-headers-strategy: framework
  servlet:
    context-path: /test/jsonb
spring:
  application:
    name: validator
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:172.17.0.2}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:pessoa}?ApplicationName=${spring.application.name}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      hibernate:
        default_schema: PESSOAS
        dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
