DROP SCHEMA IF EXISTS SUBWEBDRIVE CASCADE;
CREATE SCHEMA IF NOT EXISTS SUBWEBDRIVE;

CREATE TABLE PESSOAS.MUSICAS (
             MUSI_SQ_MUSICAS UUID NOT NULL,
             MUSI_NM_NOME TEXT NOT NULL,
             MUSI_TX_LISTMUSIC JSONB,
             CONSTRAINT PK_MUSI_SQ_MUSICAS PRIMARY KEY (MUSI_SQ_MUSICAS)
);

